#!/bin/bash

protected_branch='master'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
echo $current_branch
if [ $protected_branch = $current_branch ]  
	then  
		echo "You are trying to push to MASTER, this is forbidden. Instead please open a pull request"
		exit 1 # push will not execute
	else  
		exit 0 # push will execute
fi